{
 "title": "playground",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P99 Summary of latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "summary_http_request_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "route: {{route}}, status: {{statusCode}}"
    }
   ]
  },
  {
   "title": "Average latency in last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(summary_http_request_duration_seconds_sum[5m]) / rate(summary_http_request_duration_seconds_count[5m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P99 request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99, # 顯示 99 百分位\n  sum( \n    rate(http_request_duration_seconds_bucket{job=\"nis\", route=~\"/.*\"}[5m])\n  ) by (le, route)\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Foo Sales in TWD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(foo_sales_twd_total[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Queue A size",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_size_total{job=\"nis\",queueName=\"a\"}"
    }
   ]
  }
 ]
}