#
# Prerequisites
#
# install VSCode extension: [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# to use this tool
#

@host=localhost
@port=8080
@metricPort=9090

### Foo 
GET http://{{host}}:{{port}}/foo HTTP/1.1
Content-Type: application/json

{
    "foo": "bar",
}

### queue
GET http://{{host}}:{{port}}/queue HTTP/1.1
Content-Type: application/json

{
    "queueASize": 0,
    "queueBSize": 0,
}

### Poke metrics endpoint
GET http://{{host}}:{{metricPort}}/metrics HTTP/1.1
