#
# Prerequisites
#
# install VSCode extension: [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
# to use this tool
#

@host=localhost
@port=8080
@metricPort=9090
@time=1
### sleep 
GET http://{{host}}:{{port}}/sleep?time={{time}} HTTP/1.1
Content-Type: application/json

{
    "foo": "bar",
}

### Poke metrics endpoint
GET http://{{host}}:{{metricPort}}/metrics HTTP/1.1
